---
version: '3.1'
services:
    zeppelin:
        build:
            args:
                TZ: 'America/Lima'
            context: '.'
        container_name: 'zeppelin'
        # entrypoint: /bin/bash
        environment:
            ZEPPELIN_INTERPRETER_CONNECT_TIMEOUT: 300000
        image: 'everis/zeppelin:0.1.0'
        ports:
        - 8080:8080
        - 8081:8081
        restart: unless-stopped
        # stdin_open: true # docker run -i
        # tty: true        # docker run -t
        volumes:
        - './data:/opt/zeppelin/data'
        - './jar:/opt/zeppelin/jar'
        - './lib:/opt/zeppelin/lib/native'
        - './notebook:/opt/zeppelin/notebook/personal'
